LICENSE.meta

Upon importing into Unity, LICENSE.meta will be generated as it is missing from remote

Added missing LICENSE meta data

---

Utils/BuildVersion.cs

This PR fixed the infinite `Resource` folder bug.
In addition, to **enable the build version you now need to provide a compiler flag** `ENABLE_BUILD_VERSION`.

Build Version is now optional.

---

Tween/AbstractAnimation.cs
Tween/AnimationCollection.cs
Tween/DelegateAnimation.cs
Tween/FunctionCallAnimation.cs
Tween/SequencedAnimation.cs
Tween/TimedAnimation.cs

If a TimedAnimation was given a duration of <= 0 in the constructor, the Duration property setter called FastForward and invoked the OnComplete callback without having Play called.

Dev timed animation fix

---

Tween/AnimationCollection.cs
Tween/DelegateAnimation.cs
Tween/IAnimationPlaybackControl.cs
Tween/IAnimationPlaybackControl.cs.meta
Tween/ParalleledAnimation.cs
Tween/SequencedAnimation.cs
Tween/TimedAnimation.cs

You can now `ScaleTime`, `ChangeSpeed` and `Reverse` for any `AnimationCollection` and `TimedAnimation` and `DelegateAnimation` (e.g. embeded TimedAnimation).
Fixed the multiple callback issue when `FastForward()` or `Abort()` a collection.
Fixed a crash when `Abort()` a collection.

Tween System Improvement and Bug Fixes

---

Tween/AnimationDriver.cs
Tween/TimedAnimation.cs
Utils/UpdateList.cs
Utils/UpdateList.cs.meta

The logic of the animation driver is now abstracted into an update list. You basically add/remove functions from it, and when you update it, it will call all the update functions using the dt you passed in. The animation driver now just uses one of these.
We also changed animation driver to use `unscaledDeltaTime` by default.
`AnimationDriver` property of `TimedAnimation` is now lo longer static, you can plug in a different animation driver for each specific animation instance. - This is useful if you have scaled time, and you want some animations to be affected by scaled time, but then some other UI animations for example may be updated with the default driver
Now the update list can be used elsewhere.
The animation driver is simpler and easier to extend or implement a new one. If you …

Improvements to animation driver

---

Serialization/ArgsList.Serialization.cs
Serialization/ArgsList.cs
Serialization/Editor/ArgsListTests.cs
Tween/Easings/EasingFunctionStore.cs
Tween/Easings/EasingFunctionStore.cs.meta
Tween/Easings/Parabola.cs
Tween/Easings/Parabola.cs.meta
Tween/Extensions/TransformAnimationExtensionsMove.cs
Tween/Serialization.meta
Tween/Serialization/Editor.meta
Tween/Serialization/Editor/CreateTweenConfigScriptableObject.cs
Tween/Serialization/Editor/CreateTweenConfigScriptableObject.cs.meta
Tween/Serialization/Editor/TweenBuilderEditor.cs
Tween/Serialization/Editor/TweenBuilderEditor.cs.meta
Tween/Serialization/Editor/TweenConfigEditor.cs
Tween/Serialization/Editor/TweenConfigEditor.cs.meta
Tween/Serialization/Editor/TweenConfigScriptableObjectEditor.cs
Tween/Serialization/Editor/TweenConfigScriptableObjectEditor.cs.meta
Tween/Serialization/TweenBuilder.cs
Tween/Serialization/TweenBuilder.cs.meta
Tween/Serialization/TweenConfig.cs
Tween/Serialization/TweenConfig.cs.meta
Tween/Serialization/TweenConfigScriptableObject.cs
Tween/Serialization/TweenConfigScriptableObject.cs.meta
Tween/Serialization/TweenCreatorFunctionStore.cs
Tween/Serialization/TweenCreatorFunctionStore.cs.meta

You can now set up tweens in the editor, using the "TweenBuilder" script, it will allow you to choose which type of tween to create, and then select all the parameters you want, and it will be saved in the scene/prefab!
Just tick "Use referenced Config" and you can configure a tween in a scriptable object. and apply that tween to several objects. (The target cannot be serialized in a scriptable object, so it will just use the TweenBuilder object as a target or look for  the correct component on there).
it supports most of the built in tween types, and can be made most any of the constructors and extension functions you already use*
\* We filter out functions that have unsupported args; those not supported by ArgsList, such as quaternion. However we also make special cases like …

Tween Serialization + Editor Support

---

Utils/Editor/FindUnusedAssetsWindow.cs
Utils/Editor/FindUnusedAssetsWindow.cs.meta

**How does it work?**
When a build is created in Unity the Unity Editor Log will contain information on what assets are included in the build. We can use this information to compare against the assets in the project. The assets that are in the project but not in the build are most likely the assets that are not used.
**How to use it**
Navigate to `DUCK/Find Unused Assets`

Find Unused Assets Window

---

Tween/Extensions/AnimationCollectionExtensionsScale.cs

it was feeding in the wrong parameters to the inner function, and it's not a compile error since they are all floats. I guess nobody used `AnimationCollection.ScaleX()` extension before

Fixed parameter order

---

Utils/GameObjectExtensions.cs
Utils/TransformExtensions.cs

Extension methods for `GameObject` and `Transform` to aid the creation of child objects.
These functions are essentially doing what `AbstractController` does when adding a child. It's a useful thing to want to do and `AbstractController` will sort it for you in most cases, however moving it to here allows you to use it outside the `AbstractController` ecosystem
`AddChildObjectWithComponent<TComponent>` -> add a child to the game object with the component attached and name it as the component's name
`AddInstantiatedChild<TComponent>(pathToPrefab)` -> Instantiate a prefab as a child.
Both support `worldPositionStays`

Added child object creation helpers

---

Utils/Broadcaster.cs
Utils/Broadcaster.cs.meta
Utils/Editor/Tests/BroadcasterTests.cs
Utils/Editor/Tests/BroadcasterTests.cs.meta

This is to support one of my favourite patterns of late. Broadcasting events to objects by targetting interfaces specifically designed to catch your events. Very similar to unity's `IPointerEventHandler` etc...
`Broadcaster.BroadcastTo<IEventHandler>(targetObject, o => o.HandleTheEvent());`
It will execute your callback on all the objects found of the given type. By default it also searches for the component in the children. This can be disabled using the optional 3rd parameter (defaults to true)

Implemented util for broadcasting events to objects

---

DebugMenu/DebugMenu.cs

Update an existing debug menu button. Useful for toggle options without having to remove and add a new button, which would move the new button to the bottom of the view.

Added UpdateButton to DebugMenu

---

DebugMenu/DebugMenu.cs

Fixed issue of deleting the Button component rather than the GameObject, leaving a dud button

Debug Button Destroy Fix

---

Localisation/Localiser.cs

The localiser no longer tries to find your current culture in initialise. It isn't actually possible to find using `CultureInfo` unless you're using the experimental newer runtime; using the current mono runtime `CultureInfo` getters would always return en-US.
With this change we pass in the culture name we want instead, and leave finding the current culture name up to each project either via plugin, native code, or translating `Application.systemLanguage` into a locale if merging countries that share a language isn't a problem for your project.
Also now allows the setting of the defaultCulture.

Localisation Fixes

---

Controllers/AbstractController.cs

In a MonoBehaviour it's often useful to know when the application is quitting, to prevent race conditions such as unsubscribing from an event on an object that may get destroyed first.

IsApplicationQuitting Property in AbstractController

---

Http/Http.cs

Http now supports the API pre 2017.2 and post 5.6

HttpRequests now support Pre Unity 2017.1 and post 5.6

---

Editor/ProjectEditorPrefsWindow.cs
Editor/ProjectEditorPrefsWindow.cs.meta
Prefs.meta
Prefs/ProjectEditorPrefs.cs
Prefs/ProjectEditorPrefs.cs.meta

Allows you to setup editor prefs that you can control via a tool window. These editor prefs can be used for anything editor time or editor runtime, such as drawing gizmos, skipping cutscenes etc...
EG: 
```
private void OnDrawGizmos()
{
if (ProjectEditorPrefs.Get<bool>("drawMyFancyGizmos"))
{
Gizmos.color = Color.cyan;
Gizmos.DrawCube(transform.position, new Vector3(3, 2, 3));
}
}
```

Project Editor Prefs

---

Forms/Form.cs

Any field marked as clear on submit (commonly password fields) would clear the value before invoking the event of OnSubmit. This mean anything listening for the event would receive the default field data.

OnSubmitForm event now invokes before clearing but after validation

---

Utils/Editor/UpdateListTests.cs
Utils/Editor/UpdateListTests.cs.meta
Utils/UpdateList.cs

The bug is that some animations appear to not play. In actual fact they begin but never complete.
The problem is within the system that updates the animations, the AnimationDriver, or more specifically the update list implementation within. The update list is designed to be highly optimized and an abstracted enough to be used to update anything, not just a list of animations. It's more optimal than relying on several monobehaviour updates.
The cause is due to the logic that deals with removal of update functions during an update loop. The logic specified that if we attempt to remove an update function, in most circumstances we mark it as dead by adding it's index to a list of deadFunctionIndices, however, if we were currently updating the function we wish to remove we would just remove it …

Fixed bug with update list, and added unit tests

---

Localisation/Localiser.cs

Fix for bug where attempting to load a non-existent localisation table would still fire the events

Localisation load failure fix

---

AudioSystem/AudioConfigSequence.cs
AudioSystem/AudioSystemExtension.cs

Fix for indexing bug if an AudioConfigSequence contained 2+ etnries of the same AudioConfig: explicit find-by-index rather than .FirstOrDefault

AudioConfigSequence indexing bug

---

Tween/AnimationCollection.cs
Tween/DelegateAnimation.cs
Tween/ParalleledAnimation.cs
Tween/SequencedAnimation.cs
Tween/TimedAnimation.cs
Utils/Editor/Tests/AsyncTaskListTest.cs

- Fixed an issue that aborting an invalid animation collection will crash.
- Added a guard for aborting a non-playing animation.

Dev tween abort

---

DebugMenu/DebugMenuLog.cs

Pass pending logs back to the main thread. Unity's Debug.Log is thread-safe so it made sense for this to be too. I didn't modify the `Clear` function to be thread safe from code as it's only called from the button click which will always be safe.

Thread-safe DebugMenuLog

---

AudioSystem/AudioSystem.cs
DebugMenu/DebugMenu.cs
Tween/AnimationDriver.cs
Utils/MonoBehaviourService.cs

The unity editor does not allow a function call of DoNotDestroyOnLoad at editor time. When writing tests that spawn a view that uses DUCK tween for example this function is called and causes the test to fail.

Fixed tests failing due to DoNotDestroyOnLoad

---

AudioSystem/AudioSystemExtension.cs

Same issue as before - if an AudioConfigSequence contains multiple entires pointing to the same AudioConfig, calling the callback by config makes it impossible to discriminate between them, whereas index is unambiguous

Changed per-config callback to call by index instead of object

---

AudioSystem/AudioSystem.cs

This is to fix the following issue:
1. audioConfig.FadeOut(1f) // fade the clip out over 1 second
2. Less 1 seconds later the clip reaches the end. but the fader will still continue reducing the volume
3. something else attempts to play, the AudioSystem requests a free channel. This does `channels.FirstOrDefault(source => !source.isPlaying);` It can return channel still being affected by a fader. meaning your new sound will be affected, usually resulting in it not being heard, since it's probably already mostly faded out.

Fix: AudioFaders will complete if the clip ends before the fade ends

---

AudioSystem/AudioConfigSequence.cs
AudioSystem/AudioSystemExtension.cs
AudioSystem/Editor/AudioConfigSequenceEditor.cs

Changed sequences to return configs, not the raw AudioSource objects, since these should be handled internally by the audio system

AudioConfigSequence cleanup

---

AudioSystem/AudioSystemExtension.cs

Missing optional argument when recursive call to same function is used: fixed

Fixed a bug where PlaySequenceAtIndex wouldn't pass the timer callback

---

Serialization/ArgsList.Serialization.cs
Serialization/ArgsList.cs
Serialization/Editor/ArgsListTests.cs
Utils/Editor/EditorGUIHelpers/DrawFieldByTypes.cs

This is something that I should have done a when I first made it, but now it's here. It includes tests.
Writing this has highlighted the need to refactor a little bit:
Before the code had to make exceptions for component subclasses. The exceptions were in quite a few places but it was only for one type. I didn't foresee that this would be such a common thing. Now subclass exceptions need to be made for Enums and ScriptableObjects too. 
I need a solution where I can easily add extra ones and customize behaviours in different places for each type.
I will look into this in a different PR

ArgsList: added support for enums + scriptable objects
